### ISSUE TITLE
Param init and dynamic changing the text

### ISSUE THREAD

**Issue by kafeltz** [owensbla/frostyjs#5]
Hello, i'm on need to init frosty tooltip by pure javascript and it is only possible to do this via DOM attributes. I have an IF condition on javascript side.

The need to change the text is needed too, i have to destroy and change attr and re-create the object. It is pain.

The plugin is great, would be even better with these 2 features. Is there a plan to do it? Shall I do a fork and to it?

Thanks

**Comment by kafeltz** [comment]
Well well... i found out how to init by params via constructor, no intuitive:
    $submit.frosty({ 'content': 'Você é organizador!', 'html': true });

Now, would be nice to change the value after init, not possible without $destroy and init again.

**Comment by kokujin** [comment]
+1

I'm for this too. I would like to get the content from the element attributes
